// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/mutezebra/forum/config"
)

func main() {
	config.InitConfig()

	h := server.Default()

	register(h)
	h.Spin()
}
