// Code generated by hertz generator.

package base

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	base "github.com/mutezebra/forum/biz/model/base"
)

// Ping .
// @router /ping [POST]
func Ping(ctx context.Context, c *app.RequestContext) {
	var err error
	var req base.PingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.PingResp)

	c.JSON(consts.StatusOK, resp)
}
