// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	base "github.com/mutezebra/forum/biz/router/base"
	forum "github.com/mutezebra/forum/biz/router/forum"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	forum.Register(r)

	base.Register(r)

}
